import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "../../providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <main>{children}</main>
    </ReactQueryProvider>
  );
}
